### ISSUE TITLE
test

### ISSUE THREAD

**Issue by printlndarling** [hcmua5201/social-circle#3]
@hcmua5201 已上传模板

**Comment by CH112192** [comment]
数据库连不上，有没

**Comment by hcmua5201** [comment]
你找另外一个创作者咨询



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 11, 2024 21:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hcmua5201/social-circle] test (Issue #3)




 
数据库连不上，有没

**Comment by CH112192** [comment]
他的主页404

**Comment by printlndarling** [comment]
> 数据库连不上，有没

@CH112192 已上传sql，如无其他问题，此issue将随后关闭.
